### ISSUE TITLE
Are secrets accessible in build script of upstream packages executed during Pkg.update?

### ISSUE THREAD

**Issue by tkf** [JuliaRegistries/CompatHelper.jl#213]
I haven't confirmed this, but, IIUC, `CompatHelper.main()` can call `Pkg.update` which can execute `deps/build.jl`. If so, I suppose this script has access to my secrets? How about decoupling "preparation" and "deploy" phases?  Maybe something like this?

```yaml
- name: CompatHelper.prepare()
  run: julia -e 'using CompatHelper; CompatHelper.prepare()'  # no access to secretes
- name: CompatHelper.deploy()
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}
  run: julia -e 'using CompatHelper; CompatHelper.deploy()' # only limited packages are loaded
```
